// <auto-generated />
using System;
using HotelManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231121093038_migracion inicial")]
    partial class migracioninicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelManager.Models.Cita", b =>
                {
                    b.Property<Guid>("IDCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoCita")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaHoraCita")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDEmpleado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDCita");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("HotelManager.Models.CorrelativoSAR", b =>
                {
                    b.Property<Guid>("IDCorrelativoSAR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroCAI")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroFinal")
                        .HasColumnType("int");

                    b.Property<int>("NumeroInicial")
                        .HasColumnType("int");

                    b.Property<int>("UltimoUtilizado")
                        .HasColumnType("int");

                    b.HasKey("IDCorrelativoSAR");

                    b.ToTable("CorrelativoSAR");
                });

            modelBuilder.Entity("HotelManager.Models.DetalleProductoFactura", b =>
                {
                    b.Property<Guid>("IDDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("IDFactura")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDProducto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<Guid>("ProductoIDProducto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubTotalLinea")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("SubTotalLinea");

                    b.HasKey("IDDetalleFactura");

                    b.HasIndex("IDFactura");

                    b.HasIndex("ProductoIDProducto");

                    b.ToTable("DetalleProductoFactura");
                });

            modelBuilder.Entity("HotelManager.Models.DetalleServicioFactura", b =>
                {
                    b.Property<Guid>("IDDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("IDFactura")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDServicio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<Guid>("ServicioHotelIDServicio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubTotalLinea")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("SubTotalLinea");

                    b.HasKey("IDDetalleFactura");

                    b.HasIndex("IDFactura");

                    b.HasIndex("ServicioHotelIDServicio");

                    b.ToTable("DetalleServicioFactura");
                });

            modelBuilder.Entity("HotelManager.Models.EncabezadoFactura", b =>
                {
                    b.Property<Guid>("IDFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelativoSARIDCorrelativoSAR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DescuentoFactura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("DescuentoFactura");

                    b.Property<bool>("Eliminada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDCorrelativoSAR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDEmpleado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ImpuestoFactura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("ImpuestoFactura");

                    b.Property<string>("NumeroFacturaSAR")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("SubTotalFactura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("SubTotalFactura");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("TotalFactura");

                    b.HasKey("IDFactura");

                    b.HasIndex("CorrelativoSARIDCorrelativoSAR");

                    b.ToTable("EncabezadoFactura");
                });

            modelBuilder.Entity("HotelManager.Models.Habitacion", b =>
                {
                    b.Property<Guid>("IDHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Tarifa");

                    b.Property<string>("TipoHabitacion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("IDHabitacion");

                    b.ToTable("Habitacion");
                });

            modelBuilder.Entity("HotelManager.Models.Producto", b =>
                {
                    b.Property<Guid>("IDProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Existencias")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("PrecioUnitario");

                    b.HasKey("IDProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("HotelManager.Models.Reserva", b =>
                {
                    b.Property<Guid>("IDReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckin")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDFactura")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDHabitacion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDReserva");

                    b.HasIndex("IDFactura");

                    b.HasIndex("IDHabitacion");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("HotelManager.Models.ServicioHotel", b =>
                {
                    b.Property<Guid>("IDServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Tarifa");

                    b.HasKey("IDServicio");

                    b.ToTable("ServicioHotel");
                });

            modelBuilder.Entity("HotelManager.Models.DetalleProductoFactura", b =>
                {
                    b.HasOne("HotelManager.Models.EncabezadoFactura", "EncabezadoFactura")
                        .WithMany("DetalleProductoFacturas")
                        .HasForeignKey("IDFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManager.Models.Producto", "Producto")
                        .WithMany("DetalleProductoFacturas")
                        .HasForeignKey("ProductoIDProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncabezadoFactura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("HotelManager.Models.DetalleServicioFactura", b =>
                {
                    b.HasOne("HotelManager.Models.EncabezadoFactura", "EncabezadoFactura")
                        .WithMany("DetalleServicioFacturas")
                        .HasForeignKey("IDFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManager.Models.ServicioHotel", "ServicioHotel")
                        .WithMany("DetalleServicioFacturas")
                        .HasForeignKey("ServicioHotelIDServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncabezadoFactura");

                    b.Navigation("ServicioHotel");
                });

            modelBuilder.Entity("HotelManager.Models.EncabezadoFactura", b =>
                {
                    b.HasOne("HotelManager.Models.CorrelativoSAR", "CorrelativoSAR")
                        .WithMany("EncabezadoFacturas")
                        .HasForeignKey("CorrelativoSARIDCorrelativoSAR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrelativoSAR");
                });

            modelBuilder.Entity("HotelManager.Models.Reserva", b =>
                {
                    b.HasOne("HotelManager.Models.EncabezadoFactura", "EncabezadoFactura")
                        .WithMany("Reservas")
                        .HasForeignKey("IDFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManager.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("IDHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncabezadoFactura");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("HotelManager.Models.CorrelativoSAR", b =>
                {
                    b.Navigation("EncabezadoFacturas");
                });

            modelBuilder.Entity("HotelManager.Models.EncabezadoFactura", b =>
                {
                    b.Navigation("DetalleProductoFacturas");

                    b.Navigation("DetalleServicioFacturas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelManager.Models.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelManager.Models.Producto", b =>
                {
                    b.Navigation("DetalleProductoFacturas");
                });

            modelBuilder.Entity("HotelManager.Models.ServicioHotel", b =>
                {
                    b.Navigation("DetalleServicioFacturas");
                });
#pragma warning restore 612, 618
        }
    }
}
